on:
  release:
    types: [created]
  workflow_dispatch:

name: Release

jobs:
  publish-xtp-test:
    name: publish-xtp-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: wasm32-unknown-unknown

      - name: Release Rust xtp-test
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_TOKEN }}
        run: cargo publish -p xtp-test
